# Generated by Django 6.1 on 2026-09-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_image',
            new_name='subcategory_image',
        ),
    ]
