# Generated by Django 6.1 on 2026-09-15 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0004_cart_cartitem_favorite_favoriteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='avito_app.product'),
        ),
    ]
